---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alist-config
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
