---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alist
  namespace: tools
  labels:
    app: alist
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: alist
  template:
    metadata:
      labels:
        app: alist
        app.kubernetes.io/name: alist
    spec:
      containers:
        - name: alist
          image: xhofe/alist:latest
          ports:
            - containerPort: 5244
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: UTC
          volumeMounts:
            - name: config
              mountPath: /opt/alist/data
            - name: storage
              mountPath: /mnt/storage
            - name: gdrive
              mountPath: /mnt/gdrive
            - name: hza
              mountPath: /mnt/hza
          resources:

            requests:

              cpu: "50m"

              memory: "128Mi"

            limits:

              cpu: "500m"

              memory: "512Mi"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: alist-config
        - name: storage
          hostPath:
            path: /mnt/storage
            type: Directory
        - name: gdrive
          hostPath:
            path: /mnt/gdrive
            type: Directory
        - name: hza
          hostPath:
            path: /mnt/hza
            type: Directory
