services:
  searxng:
    image: docker.io/searxng/searxng:latest
    hostname: searxng
    container_name: searxng
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
    volumes:
      - ${HOME}/dockerc/searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    networks:
      - public
    # ports:
    #   - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  public:
    external: true

volumes:
  searxng-data:
