apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: default
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:gyqd5fkv5t4=,iv:beeMuq7a1edPKLrW+uFDj849zHpWtS1exIR9dm3w/H8=,tag:awDcrSZryUEz5FSVsj4HmA==,type:str]
    secretkey: ENC[AES256_GCM,data:nXwdK09OG9o=,iv:q9wl0ZsrchXHw0Ju/OHC9zL3kQHFz4dne0HpBFlZ90E=,tag:iIRu5XmwB8+sLqjq9fLMOA==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUnlFOVoyUHlONHNSZmVX
            L2pXa3hpSDI3Q2ZXazAwR1VzekcrL2treFZvCnk0V1hNaDRicHdQM3l1VnhaQ1Vs
            b0QxUlZyR3RmVklnZDlSaHQyaHg2RlUKLS0tIFEyMnlsUy9lRExNbWFrWjN0a21S
            UlN5cDNKb0FmWU90NlhRUDFVYVlnSjQK4i/g4hgzsWmsWvT7/SHCV9X78ovQnStl
            +9FVqXl/7RqtFyNt5Lond8HKJdbUqgssqZvM8MICJF0T0AblsMXvnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T04:20:49Z"
    mac: ENC[AES256_GCM,data:B6aHkoG+MVIQ0vWvQTHIJ7rsRT5QldqoyciQGJwU2xBGc2olJ02A8vvPRVhj2Yh3UpGfIlwrJe7dqAxD9Qs4Gh/otYqNZYrkIpBDFR1diVvYax9RmuTmAIY1ZCiE3J4EZHYuFbh+UYbjGYelrNSKk3i6B9io5PwfElys2bwVHBo=,iv:KwD0EM7yFMMw7ZS72/KNJlJabP/8y8E/hMQB1jsUdMQ=,tag:TCWi55RSU12ICQF54aYKWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
