services:
  n8n:
    image: n8nio/n8n:latest
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - GENERIC_TIMEZONE=${TZ}
    # ports:
    #   - "5678:5678"
    volumes:
      - ${HOME}/dockerc/n8n/data:/home/node/.n8n
    networks:
      - public

networks:
  public:
    external: true
