---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keel
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.keel.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keel
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: keel
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: keel
        namespace: flux-system
  values:
    image:
      repository: keelhq/keel
      tag: latest
    service:
      enabled: false
    basicauth:
      enabled: false
    webhook:
      enabled: false
    polling:
      enabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"
