---
- name: Run cloudflared tunnel
  community.docker.docker_container:
    name: cloudflared
    image: cloudflare/cloudflared:latest
    state: started
    restart_policy: always
    network_mode: host
    command: "tunnel --no-autoupdate run --token {{ cloudflared_token }}"
  become: yes
