---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hrms-db-secrets
  namespace: hrms
spec:
  encryptedData:
    mariadb-password: AgAD+x+CCvtBY+dnX8TUH/zq1a2X+99KS69g8ZToMwkSscGecVdUVe7rbd4gJe0REsRCXoEhn0xdkgG7MWxuFrT54DN5V/iQgJhJza2gG4KF67UufofWYVH0Kz4sDAjkcr7zwsSjc2DhMRcE2mI6lj7ZxHlYS1Z0NYrg+PpqFhWYFzHO0mqXA9HQL4nsW7/cvVF2UDcXtVezxTAhUbIZLtg4XIU7lA3Y3vIuLjGUQCwnBCZvUWbb61R31u8B9ThcnHliz84NFwj667KaRwG8cJ2kWn+5qi3d7ysYGn6ZUC0TQ5jpwUuP53XlAbA6drFxPQkq5eaxNgbipg/C6oZZprkABw2qYRVNr5BvJKEDFDOmL39cTxcGkaRkFZuFRq95K8gM1dNskKzNB7L6BIcVugoOsTQUCFw27NQTbbgfu0SsfqGloY51oBxx71njfdJSQx5gPCAZGDcOpn7N8PciWVq8YpuKv9TlcIjwk5bPvt7zymqMorBOcEf6fSW5A/m2FcyYjgG+5KTyI3ZTp+xtAvuJB52WnLvR85OYa0rBszlR+fdS9JJMiXmYO2qerwq8dcOtp8xnh6ADUwU9gL6ZZRBXuB0cWLRleFtou4xtT2GRBatXQq3jeN+9In7qmxnnxWKqinpfWybAGYfF05eoqKtRHRf+DcZC6b6tWfXNbUyoV0LoCeCamiGHIsi41I6m0fUfJtEAmGBF+CaH9+juo6j9Ht8wOaWHtHbKkrF0V+eCVzMuY5r403oOaiOEV9bkpRc=
    mariadb-root-password: AgAS3gqCun+s7zycBzvP0zCIpJFwLaFFoJ2RqFoaPWPUOha47dvz8WIwHDICPvd8VnNe7TAcxzc0uaHBoghEgwHgdwsmA0X/I6+6GEyZnali4myVvl2cjpNo/f4fPr93Y/RsSrrnpp4hKVvsQXIroK04qCOO1w6XY64ZO+J7RzRE9SQRGkkBeMwdg/1FOFfw3CdST1/hBg5a1KkOefI3Qza/Rwd2AboTk0HRjkcJLRyJahsf2rbv5OQUiTSyFU1KKBhvJqCpXqc4yHVHVqago5L4JgNgsB7dbO2LIBnluEyXH1LvgfP/k+y0sFt0RaHoAfUwLZCStckzto/kwoCVxV/3GHBUFl5JBx6LcTrckOyVxNej1M+Bcb07a32PAKU6AtlNlbyan3AnQ5K8/BVBhC5kWoacDHfUMzObb6LE4JqBksjJdsHFKVMg8gJZ4sgFS9qoTcFDhuWSC/JTBr9dvIZZPo1vX80l0NEZqwyHOey0xiMfyirMgmdVG8MM96DYzQOgm24FiIPr3K3QVC3dPSBMf5MZL8L4hDif5Yhk708/JzYHv6J5jzWnOB1ywyqln8mQO5y8EPALaD/mvpvAVQxmx3kskok79BhR8lCFtUjab965UVVqk0Hbr0e+tRMagHrUQNfP2vSncyTeuqVMDVbl3gctAA45pPhee9u8SHo3uoWi5Y/NMGZrlqRWwyG8eecz2o4ECyqaQGR2UJJnI7t+yc45n2+NsTW//xdAJtNPQ5SiMIjKXsGC9CD7iTBCn6s=
  template:
    metadata:
      creationTimestamp: null
      name: hrms-db-secrets
      namespace: hrms
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hrms-admin
  namespace: hrms
spec:
  encryptedData:
    adminPassword: AgAaSk8sN9js/jNdEEUhlu0ZMLdZo4z61wBcEmdflU6GMboBkKbI+Ey/iG0/GY5vTV246fdO0onJJPYHrXcWm69fFGkmII58A7K9/fl0cWKyPOLZY+yxbX3iKoBXImDsVC92tdEEJ0cQ1VlnHlBq0L5HoLjl0lDw16DkKSItAMEo9yIaVlSgGAp2ss2BKi4Kgj8pgxK6CBwMnz2OdvkeWb0PsEfB00TUbeVw7fR4ODtldCReMY52uVCxedJcm8VFA1nS7d/mDogOnFWsJiWB+x93X2PWTX8cfN5QOFDb44Nlj6g/3Kj83lu5YRdNLZD+CqBEn9a2FdKmQYk8dwNUyWyLTnq0UC80YbajkVsqdpxAcfokVLzyzf9thOWylWXTcSifIr/uJ3mAPK6RqpCiFYww4PwvsuX9WJI2HhK/MUEp97V9llzbiGgOeOdQdyGNT0N1wXu4jRItVyeWw548Wx78sXieKVZh0BnH3aSGzoOID49GCCnwxE8X8XIBVFKzpmWjpVLylouGtigiDrXEXW47TYfRs28t8QyWLVJPJJ/oS07VO54FcJeXAlNttg5+M6u/dFShsQoSvAPbaK8a076s4zHi+FPnx318BsFo9zLYVPQaYfb06oBNoDqlif1r1RpHvK+eqlYzBPCwMfGDedxgiFm4+sgdOF4LvNlsT1obxqhypxKD0rMZvCHDl3fqyWKa398fWgZjYpJYoiCziL9JgcyU4N/tM8zQ5U8ua6sw9Q==
  template:
    metadata:
      creationTimestamp: null
      name: hrms-admin
      namespace: hrms
