---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: piraeus-storage
  resources:
    requests:
      storage: 10Gi
