---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: games
spec:
  clusterIP: 10.43.111.111
  type: ClusterIP
  selector:
    app: minecraft-server
  ports:
    - port: 25565
      targetPort: minecraft
      protocol: TCP
