# Generated by nixos-generate-config — do not edit manually.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" ];
  boot.initrd.kernelModules  = [ ];
  boot.kernelModules         = [ ];
  boot.extraModulePackages   = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/81a751b0-3989-45a4-be0d-804b88a8720e";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/E670-3741";
    fsType  = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
