---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media
spec:
  clusterIP: 10.43.1.13
  type: ClusterIP
  selector:
    app: prowlarr
  ports:
    - port: 80
      targetPort: 9696
      protocol: TCP
