---
apiVersion: v1
kind: Service
metadata:
  name: hermes
  namespace: hermes
spec:
  type: ClusterIP
  clusterIP: 10.43.9.9
  selector:
    app: hermes
  ports:
    - name: gateway
      port: 8642
      targetPort: 8642
      protocol: TCP
    - name: dashboard
      port: 80
      targetPort: 9119
      protocol: TCP
