apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-runner-secret
  namespace: utils
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: github-runner-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: RUNNER_TOKEN
      remoteRef:
        key: GITHUB_RUNNER_PAT
