apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: github-runner-data
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
