---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tools-auth
  namespace: utils
spec:
  encryptedData:
    password: AgAwhcxGX0/BDjJd/IWqXWD+Kg4tlMnKrZro41EJW/R4Zv4jxtohNarg1doZFVFdF+vh9mD6R34X/I2JoXeXNRDX8IoufWSnu1wS1PVhhymM2NE6PTpjJi4+wAb6eLmLkIxt0awTfW5NovdMXLKvxXugI3+N+xRkrlRLGy5XAodH0+GpoAs17SvbmKdwfKLpnQOLvV16uRNmD1uMDJRdqKfctZUBxcuYMSf9lHmx/7NVQpA4Qnj9rvURY9+6qDTxtKFrZUIF3iP34mxVpiMEnMmv3ydBg9YD+i0PNnRq7WgAVN7biJIbNheYTx/doJ8LQF1lQXtYCLceTkLth/7Q6tnfgsjnaVOalIPTfqCVplAjBtVQotuU4jPgKfaQs4wgTO2Ku0h9dKng0bH68qjqXBPX6d6iMsg1LD0gK8d0yA+EiIPDU63J0F0erZ6YdYpLBqWJMB2/rRGBBi7IhFvJDI+EKD4N/RkwWDxanVUDCf3P7orQNW+R17GA2PZUOy8VpfM7uw0RSnGtTsINsjsDXHQxRGpPlijuuEeeSKNjCFaDPCs6X+rypKQoxONd3bLrLk06RkGlEsnfokudTbIx5czKKhcQG+GBIpj3m2COknsJJnGz0Uv+orYC4+GeAapz8o9hYirqocHv0RHCCXlA8ElmhsyRFhBTpm6/knGfkTNtwzNEo97ATWy70rK4q5JrtSlQdfybe03urxA=
    username: AgALQohZHTY9pL5waZENqr458uUzWA94gMcO38moYS8UtFLgILbgpAsC/PQZnGGeTxbxndEJJvx3L5gw5ezrELp4QFBz7UPAKPDnOyFyBss6mn4mMnYuJ02QUXOKvj6gUyX7wlvv/G+6uSUBvSXzab4aeQnhlV+D6k7v55QN19BKRkEsisVkbmJtDouqYA55x8q38+Hn1iGNHlmWWPN2Qhy9QAThX0NMLA+jibWcYM3qoodRuP/9XnHp1vidqLbldHxRijXgoAcc+J+Kd39VtZMvaoVTyZduaJJ+ysrkP65YzDhB8bl4UCaSgUzuAacwkfCsrXA/nO8FgsaqkLa+Oq+GJfoS0OIT61TfQtWptdZvAPKke/FI2Y4Vx/cetoP+017CfyyCWGN5S1YJD3qenbRysgdrIvnLWQx9Nj21J8FYnipc7gOHP3v/tjQXD0dfB9RjhSqZ9a+1iivLbUpKzk/rrswN1eRYFZ8IzwZ+v6tlqzGfAevYG3UP64tLtb1wyVcWnnQLse8l9FmbJb/pPDopZfkuX6p2KjNif/GNVXXB4VRdNHaTw3WheYcJywHvLrP28i3Tr18GzqnqePRd7AzXgtq9qYa+d0yE0cwBtdwGfFeBgXRR25MigBVQybajfPZStw1g9rVOFPGmB6EpWXwIkcEJ7OeIdTs0u+42fLvDj1eRYV9U3Vx4ajEB4GJSG4NoDjkocOTe
  template:
    metadata:
      creationTimestamp: null
      name: tools-auth
      namespace: utils
