---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tools-auth
  namespace: utils
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: tools-auth
  data:
    - secretKey: username
      remoteRef:
        key: TOOLS_AUTH_USERNAME
    - secretKey: password
      remoteRef:
        key: TOOLS_AUTH_PASSWORD
