apiVersion: v1
kind: Service
metadata:
  name: seerr
  namespace: media
spec:
  clusterIP: 10.43.1.15
  type: ClusterIP
  selector:
    app: seerr
  ports:
    - port: 80
      targetPort: 5055
      protocol: TCP
