---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarr
  name: sonarr
  namespace: media
  annotations:
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sonarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarr
        app.kubernetes.io/name: sonarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: TZ
          value: UTC
        image: linuxserver/sonarr:latest
        imagePullPolicy: Always
        name: sonarr
        ports:
        - containerPort: 8989
          protocol: TCP
        resources:

          requests:

            cpu: "200m"

            memory: "512Mi"

          limits:

            cpu: "2000m"

            memory: "3Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /tv
          name: shows
        - mountPath: /downloads
          name: downloads
        - mountPath: /gdrive/shows
          name: gdrive-shows
        - mountPath: /hza/shows
          name: hza-shows
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - hostPath:
          path: /mnt/storage/Shows
          type: DirectoryOrCreate
        name: shows
      - hostPath:
          path: /mnt/storage/Downloads
          type: DirectoryOrCreate
        name: downloads
      - hostPath:
          path: /mnt/gdrive/Shows
          type: Directory
        name: gdrive-shows
      - hostPath:
          path: /mnt/hza/Shows
          type: Directory
        name: hza-shows
