---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfersh
  namespace: tools
  labels:
    app: transfersh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfersh
  template:
    metadata:
      labels:
        app: transfersh
    spec:
      containers:
        - name: transfersh
          image: dutchcoders/transfer.sh:latest
          ports:
            - containerPort: 8080
          args:
            - --provider
            - local
            - --basedir
            - /tmp
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
