apiVersion: v1
kind: Secret
metadata:
    name: homepage-vars
    namespace: tools
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:DhIDth63wiD7qJ30G1lkxkcLybM5RRW1BWxpGpPHo1Y=,iv:DbXw35OOBYKdpBdJnA+/2odmNKeuBCQa+CKYJCN/u7k=,tag:WE7a1l+B+gldsep7czCi7A==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:xLvkEPFiFoahQ9K9rtu89hW5wxR5HN8aQeSNwmJxLUU=,iv:rxwmYotNCqLzP9T2kLRQs+Ztz/jTbVhbbrxyDr4gH5A=,tag:FGKNTHJUzzXnU9J+alvk8Q==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:NdOoO+VSBQB/wHTilY1/9dctNASUOmc+qReEuL86NMM=,iv:7gBZYMt9vFrZKJIQo7dRYkA1b/sq+sI6XabJu6+vwdk=,tag:9Ld0LQV9wC3ovj0xAWhUAA==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:tqhgpBEop3aDbMkDeGuBZfCB75qXAxHmUXwHdozjZZk8KzBToINOx1dMEsdCS22AZwKrHbIIhu028Zizoz3b1t0JNhk=,iv:boChTXTI3B4GfJq+2NdScqnxA8uvtet8xSqZ6exuweE=,tag:/RLNeKkJjDuvow3LrgMv6A==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:Zfvjx0xwb5ChtzOR2VSEuQJi35dJlucv3eGusJ7y+30=,iv:1vrJzU2PTX1bWamFFV7yhYB/VsBCtKD+Qeck7p0L4Lo=,tag:vmu2F1xdlGtrKYNRmNnl5Q==,type:str]
    HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:dD9gG9J/Xg==,iv:JHMYBNLFO/2kAkpunleaV2Jgi2eDRAWpG7xv9xjn/kU=,tag:HpoPg7AIK1cl9Yy13G3O3Q==,type:str]
    HOMEPAGE_VAR_QBIT_PASS: ENC[AES256_GCM,data:0NkijhUfb91B6XB2fIqyBn21EQ==,iv:cpjur5DYI+3IiC3f6AQ+yBYcL8bNSwIt51G2DD3cMQc=,tag:lUYvvHnrbZ2FZnhokstE3Q==,type:str]
    HOMEPAGE_VAR_QBIT_WARP_USER: ENC[AES256_GCM,data:FzFJtHc=,iv:8x7phjyBQxgMwg+XM5ZwbJPsuJe5nYqgpkmjIBUqh50=,tag:CTVf8hARTwhWTy7YmvxzeQ==,type:str]
    HOMEPAGE_VAR_QBIT_WARP_PASS: ENC[AES256_GCM,data:Kkq1VoJ82w==,iv:LRToHGkpBQSyv9HV8WyQ3PyiUiNI3aIg6T+KDHWslq8=,tag:6CeRRaDFvMYYvgp0KPPyvA==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMHN5MlNWaktyYzRMUjhl
            VTZVYjB3d25RMFNMSDdsMy9iWUdvNjZ1WHdzCjl6T01wNWJTaElLYzkrNWZhUzY5
            Q05VeGI5Yjh0UXNsYml4cnlaY0taamMKLS0tIGZuMU55UlVuTjIxOTRPVE5sTitB
            ODByNWFlcURHa09IaUJ0TlJ6RFRVNXcK6LmpoWfNVGrXnNMvRVUGuGemAnCfPFjI
            v4jc23URLVGQqPyrXJc+fQg4RsDk90pXb+IJO2wVuqKzKq89HLp/gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T07:23:13Z"
    mac: ENC[AES256_GCM,data:pTZssioCfKD4eTiTWZI3ePfqGUSQ7WvUnlTw5KU2d3AA53yoEUSCCipxucWr0+5mD0cc4Ufa47oLGQ2aQEsoSksybLhnMbOoIxVAEWyfb0PXkExOe8VfzfeF1uGC7R+6RJHLqeMfqikcY0FQWHZwJ7AaaUlFq6zVWFcUfa5Kp+U=,iv:bHGICUcjFQeLmXLGFmdGweq6uRdZbXNx2+mwuOHilbo=,tag:3qP2wvQ5Y1WCTm6k3pOnmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
