apiVersion: v1
kind: Secret
metadata:
    name: homepage-vars
    namespace: tools
type: Opaque
stringData:
    HOMEPAGE_VAR_JELLYFIN_KEY: ENC[AES256_GCM,data:RTDIQVMkLeNVtKDPpGEFI8imu2VpZDcHQWDVq5Wz/DM=,iv:V++zAxBxF2gg0J0dUhnWrwy6PUgzXMrYaTzC6Ph/RYI=,tag:TL4vc2aX5F4dmoKNeuNHyw==,type:str]
    HOMEPAGE_VAR_SONARR_KEY: ENC[AES256_GCM,data:6pMLOw/DcXFtIOR01+D2Afw54gNCkqYCTYyEfJOzijg=,iv:DvcPsAS7MzPX8aQycf6VszE8MLAAiwUEpzC7LQOo07E=,tag:y3iizkXTbPSCd1h7HItqWA==,type:str]
    HOMEPAGE_VAR_RADARR_KEY: ENC[AES256_GCM,data:DjPz/e1CVKVrmsD9y0f08OR/B6nf1CpQutHWWGxWeiY=,iv:9LuP34mTSR8bVhDaqTfB68GlMIq/n8UfimxIcXFewJw=,tag:qJpmAA5Wi/1rrzdnl6Uwnw==,type:str]
    HOMEPAGE_VAR_SEERR_KEY: ENC[AES256_GCM,data:AckpzVDdfrcZmliOP2cnQfacvi5Xxq5lSpV/O7z1MGZBKEVlPg/Rd5K4oFVhFPxDi0Z6/+3dDoLgL4hGwesAERMAQVM=,iv:vKkjZ/K6JKTZxW4MW2beNb6ezWYS0ELmj5BwtNtnLO8=,tag:Cqwi4M3GB6AeS3IrPLflXA==,type:str]
    HOMEPAGE_VAR_PROWLARR_KEY: ENC[AES256_GCM,data:SIAp57aG26cjKb9/Dxecb2xLIlLKHktlLW7bU34XOiQ=,iv:DoQVst/S59afLSImoQvwV25oXVRuaTgql6//onQGtew=,tag:8RzcnGD9ueFTQJfT9S08vA==,type:str]
    HOMEPAGE_VAR_QBIT_USER: ENC[AES256_GCM,data:RaiSjiaqjQ==,iv:c6oI9bI6NMOHld4mVH+2U+OPWOhmk6fgp9+oxC2VSa4=,tag:J5CVy3l40yCChwAriEZTpQ==,type:str]
    HOMEPAGE_VAR_QBIT_PASS: ENC[AES256_GCM,data:I+IEdBWihRqKV8nDvmDXiTV5CA==,iv:DRa8g6mFJD9tmtFH0mnOMqKufllcnjdideiFGvSusoE=,tag:3HUwydH4bI1lsxR1iQdyJw==,type:str]
    HOMEPAGE_VAR_QBIT_WARP_USER: ENC[AES256_GCM,data:LjPj06o=,iv:XiLnG+l7gKWEBAL6n0QvhV+uqNuU5U3BzeCsyxHFdAE=,tag:97uo+JhJT6BZaKhDvoeCsw==,type:str]
    HOMEPAGE_VAR_QBIT_WARP_PASS: ENC[AES256_GCM,data:tsBu0YHBJw==,iv:GRjm/dmPhDG4FRc3tzLMEAIZbF1a83pr62/29d/ezsM=,tag:0BRONgk9j+hhUaooakAZGQ==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPWGFtVmhEWXBUSk9pZ1hi
            Vm95REN1cFFMRUFDS1RwNVZSMXg3cXEyN2tVCnZwYkRiZDh1Q1JhNlB2ZXpzaHh3
            am1XYUlHNTNzbS9nMjg4cWY4Q204bVUKLS0tIDN1eHphSmtKYVFCbDR4Z2dCQzdU
            SEpuaytvdVVRcEhrU0FHMndsMHRqRlkKQMbanE413tXqquZyJ1orUDO8f1NzGgwz
            NvvF2f49U3E9dTJY0dsRQ7f+YCkTSmYdGxH2gIdR/ga+w97pcofM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T07:28:58Z"
    mac: ENC[AES256_GCM,data:yt5ppFuU2pSaeheKvcCTqxm3MTrEq8jS2CJrKbVhp98IEmcdn0Buxpif7/JYpjxim9z2Zcc0JjiaTaPXWzTaRQ2Ba+OUEkMeqnxrsspfkIHZsz3bgL4fu/Ym9MjdRc38vMh4iXnQllExj/j0XkxSO98ewCQewjySobQsBa6zAqU=,iv:9yyvs3q6W9t3/FahN4iy3l6pqlV61qWh4lzlReYXx8w=,tag:Sta+w9e5z2dB+i6ycWjqsQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
