apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: default
type: Opaque
stringData:
    accesskey: ENC[AES256_GCM,data:W2HBRKXEl4Y=,iv:G9MmgYqBunt0xRx4nRglN+744ADQ9HgkS+OdaHYfB+I=,tag:eZL5RdoG3dE4ZoMwCZt5yA==,type:str]
    secretkey: ENC[AES256_GCM,data:cxc1Kt0GqFM=,iv:o7UynDZVtZucys4eLgyjoyIKg7J2xT087KblTLapBXg=,tag:eO/Mc4i0P6IXYSuMOfbcDg==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtWVlDZ3ZmUHNDaEVZV1JN
            TGdjYS9ObW9KVU1kWUNUbitPVEJqdmZLQVNrClBYNTRzQW13YnJJMzBUMGVWeVdt
            QlBQMXJOR2tPUWY2UFVNcThNYzVSVm8KLS0tIG5ud3VhZnRXLzlIbFRhcFBYZGlB
            elhaZ3hUMFZQKzBUek9KZ1FUTTNYNkEKKbvApfXMleBQX+XjRwGE8KKLHaVk7rxY
            rt05t868XykaG9GucKdTvDP/rWctZyyzOqBN9iPJiWyfdzUjYWqayQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T05:20:03Z"
    mac: ENC[AES256_GCM,data:YXgmZ0cuSNiLmFNJ52Vr421xc8PWjathM20OloiFQuLkNh8LL7G77tp0fowAXWYfd6xQ/Xp5zebIMLPRsCF5GdH72/8usLh4jm7aDhjnIgQpyZ0Ia7z3Ojap+eRZK3dkn6cdrOmmag1+LSWrzMOgcZ+2aKJZL9UPS+zrKjWE9A0=,iv:SunabR2gqpNJYWj6xo/VCamUpqW1/vUm0ne4mcc+Brw=,tag:w6qNloen0PD/Xjp90BAifw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
