apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: doppler-her
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: doppler-her-token
            namespace: default
            key: dopplerToken
