apiVersion: v1
kind: Secret
metadata:
    name: ai-voice-secrets
    namespace: ai-voice
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:If6k56UGONDKq19iBGunlgxvRRFip1+m1wN7YpzcKCDGf2z0Qv3DLxAi1sSHt7JZgehF8EEF++DOCzTJVpzUKJsZZUpK7Z64iw==,iv:YZ8J3Au1nKFXWDaHs+cjS6gTKQpiDSHkMkDkukK8VGI=,tag:nEavHcMUCbTqL+OxT51Zyw==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:gdc7064N+jty/fEWi0kJzmHsGaGUj44bwQDRZ4nsBiuiXveqfT5N0XAHvdUsTkJ78qXg,iv:9lUM3rtO0EH+SgtAEnYwhDtjNTQgcKFAkQFoakUnX08=,tag:yQNvcIB+eBp1rssp9ImKCQ==,type:str]
    MASTER_API_KEY: ENC[AES256_GCM,data:RQoYXXN1qx00HrBBlVU7ny4tTdraSwdHAHtn/5DhiBntkR3kvbdN93W4i/HxwECB,iv:w8WepaQ4+PGOS2qFDV4GoN9+XY+DstbjADXdz0UzAUI=,tag:RXIL4RlbXP2mDrKLtFsmoQ==,type:str]
    VITE_API_KEY: ENC[AES256_GCM,data:cct/7mU/xTG/SFH8JVEiUYd94berTwHqE9KXdyFjx/EVfhnUqg==,iv:FvmsaaOjdVlJzxZB1Qynms6Ye7zA3eW4O5SUEm3qxfU=,tag:6XclT7GJOA7ZwV+AEjinzA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:GCriUf3SZ9w=,iv:9j7lEGB2Qnx2Wx1S5LFMrce5ihrNgY8yYCkXL3jEpE0=,tag:Bf6b/dbxWD8wUEJuTLdeBQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:MCUPgF+72kwJ9t0cfrJr4hVY2guuN8Ge5d73PooXOEZp/tO8UlJbxZOu2Exnh2rG00nGo4wR7zLT8crpGFxLKxkqSHjkFRXO,iv:S5dgT7bmsCvp8LGd2L2hlWPKEvSCMGyhZ9F6S4Cxvic=,tag:LAxX1DQmgBjkyLuurCT2+w==,type:str]
    API_KEY_HASH_SECRET: ENC[AES256_GCM,data:jPPTNFdIavcM7VwIHvSmp+CTljxlVfiBfHxDC9+QX0B4DcFjgxSdGBfkoBHUMV/mZ7GcA4LPDPMILM8FNcufMw==,iv:Q2/mXZubnI5oJCDPiRD3Ede/F3M2JkrLzhUw7Qmd2ac=,tag:SS2261lWCwL8xCiWA6uBjw==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXJwaUt2Q1dhakpoUVB5
            OWRBMFlRV2VTMVJudGR1ME9QVmRpLzhOY1FjCkdrazFFS3V0NE5MNFlNL1VWTENB
            RGw3RCtFdHN2N0tLNDVScXVLaFdWM1kKLS0tIE5yTlpuY1lManBsZ2pad2RnQ3ln
            Z056RzAxM3BIMmRGenp0RGg4T3M0OEkKZqUdggVYM4qjFoGWyu+G4Z3KcOpOJZ15
            BTrUWUm2T7LQvjJfQNgxE4G7E1ubANLHZl9jKaHU6+mWFjtqydEoAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:59:08Z"
    mac: ENC[AES256_GCM,data:jPIFNBt/PLKwuK8qjlRvvt90juHNecw3KyhzBCsen6gmdpKT6SEcncUjQIajTusr20PMsO0zCrgFl9T3+0ZN47yHholT7g9UmngcWYws5oY/ZmynlonxcTQPb6S7kAuKti/awyjyRtrK7bYzOLpR9HXpQH7yAJAa2gn3aBH9Zbo=,iv:uex4ik3mDNIF9V3OPAFSc5IB3+Lt9fUiu0mm2vSwkuo=,tag:IvPW+7IdI43cNVa4qpHaCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: ai-voice
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:QhkvTxDNk8BuZ4bWQyNonWEdbKfUInniR5T79TsgtgDhPJzY1lLlwYDyvBFDFKLfmYC5isKxi0TImSpVLNDX9OWLFwKTj4nCIsis7jyo+ANt5zNCPX6sBY03GoC2y3CsJ4dnTJmkGAnbFsAnlVz3FXf9Uh6R9uqDmhe8OQDRL4g1fNw+zWMyS850tCh2HsZ9xsZoz7poXvayDfvUz4R1sjx3rqA8d6SYGq+UQA==,iv:U7bjXAeO+ObRmZhpn89AOjlLQdcaHCPTrcMLpO9Vus8=,tag:PmIYFX8TOIeI4bzf+SlD2Q==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeXJwaUt2Q1dhakpoUVB5
            OWRBMFlRV2VTMVJudGR1ME9QVmRpLzhOY1FjCkdrazFFS3V0NE5MNFlNL1VWTENB
            RGw3RCtFdHN2N0tLNDVScXVLaFdWM1kKLS0tIE5yTlpuY1lManBsZ2pad2RnQ3ln
            Z056RzAxM3BIMmRGenp0RGg4T3M0OEkKZqUdggVYM4qjFoGWyu+G4Z3KcOpOJZ15
            BTrUWUm2T7LQvjJfQNgxE4G7E1ubANLHZl9jKaHU6+mWFjtqydEoAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:59:08Z"
    mac: ENC[AES256_GCM,data:jPIFNBt/PLKwuK8qjlRvvt90juHNecw3KyhzBCsen6gmdpKT6SEcncUjQIajTusr20PMsO0zCrgFl9T3+0ZN47yHholT7g9UmngcWYws5oY/ZmynlonxcTQPb6S7kAuKti/awyjyRtrK7bYzOLpR9HXpQH7yAJAa2gn3aBH9Zbo=,iv:uex4ik3mDNIF9V3OPAFSc5IB3+Lt9fUiu0mm2vSwkuo=,tag:IvPW+7IdI43cNVa4qpHaCg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
