apiVersion: v1
kind: Secret
metadata:
    name: ai-voice-secrets
    namespace: ai-voice
type: Opaque
stringData:
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:w6BgzY7yOBXIvX2LVn2zWQ5vAJWBrBkaOF96lxeJheyHgTdkmvjJSWV3T6OqJW7k36hl8I/ZH7cvWuHCRoJd5rY91zzbmwvFxw==,iv:IO8wlcGf95EihIv4nfQvxUoGHFPi3CabRdKiIz9d+yg=,tag:/ima4yHsYauAfLE1bv48Sw==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:FOKK6xE/+8nnTjfBmIb1xA3lFDOhhnndYdUmJ5IajJ34JKOdy1AJMCKjSstD2VyEUhtW,iv:ziG1z7sYaxR51+Bwd22A1SG/o+2owvcGR86CM/eELYQ=,tag:mYR0Kd+//RGjzvs5w6fJ9Q==,type:str]
    MASTER_API_KEY: ENC[AES256_GCM,data:TcDO/w3v7tOqerJBUVUIgv1YZ90NY+YLx8N+U/TQYjdhY7dvnCNCStYnGQDMPYJj,iv:eHWs3Y0ZYIqbtjrrHBvWsMk/xX3lUClj0XvdsowzIak=,tag:GFRYkcYQ0B+MsKZgL2dTNQ==,type:str]
    VITE_API_KEY: ENC[AES256_GCM,data:ZvZuNiR3wZMfkHJA9RK+1ufuziTzXghtIzGa+CCVCh5SnB92vw==,iv:UThFPkJ4NWiKG1OyEcNBfd+xPEvO6UN901ctyl4/rX0=,tag:v/zTYzAwhSkimDdIh9QyrQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:0DVFvcpcOyw=,iv:QK3F2KjY5SpL8bMAJvKHyqrzvNVCpGRFvmaH7TEkZrg=,tag:xLRrOYUJpdX0yHx8TCOYeQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:d4NAv8SOyGVHXBV5gx1FvvdCltTSdMpgW6KrYM0F9UwvVzMgQLzatPug7FhPD2NlfroTMTDOWRjQyvJ+H5j8vE5NmqiDie/K,iv:s/lIHXtsCgIZRhy13d+rxmvWzs5L0GORMI5dpLecsFI=,tag:6eu0Nvkhrp6cLpWF9zEK5Q==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieHU4UDhtWktURFpZZ2RI
            Z2NvUnczNkowcjVjaHFNTDVrMEt0ajFuUm5jCjA2ZDg2WlRlWmVkVTJNaklTM2lV
            WjRaRVl1WndYd29mV3ZPMTFPNzdWWVkKLS0tIFArSGZiU1pVN0toazhvd2N0VjZw
            NHVhZjgrVGd6RlZ6c2V3aUJYak1uY1kKru005TtTCcWjW+mRKb1lg2wTO0wh3OiX
            w4QJ3K9lTD6ySQiPK08ksuysl/xftZY5VIP59KEbpv1V7O3/NlVv5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:43:20Z"
    mac: ENC[AES256_GCM,data:uAJCIyjrgvESNf4xGe1AHUB3Xd6DFmifn1Gyz1uGFtkAF0dVX/l49uf0ZbaO1nUM8nHyBGOeN152WLWVwCf+tPK8uRu53Sci7CJskR6GEFLfippmsdkrbLjWLL1eaAHC2JfXeOj8MR9tVqlXY9+N2EJFkTAeLhpZXhYI6eV8FmM=,iv:5yav4tk0L9zo8xCzBc9u7So6MeproCVt2mDzSvt4HX8=,tag:EkwNcjyQeSO9OVkEz0GlOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: ai-voice
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:1AquCRquAwHv20jvab4U4uH3S6rn7F2vS4b0cDNpxTJ11ol+5u6pRqcZ4/ULXJa1xABmhD2sclz+LmZfr4YJGzxCZGrl9eR+Pzr1nccqEsAPlS0j3G0SnpJmlYqpmjbN62KgKV6QKzYrzNMuZ3iRqQnemMrKR8l6g0fVPKH8ODwNDHpQ5mpXzERYxDGoSTfllWTSo9d3rbxXnkw/M91l1DGySNVqCTdt+JECFuB1X941+8XLYBbYXL8h3IWMBph1AX18ZndWo8RQjomuBebvuWC3gGxFcJRnxFy6kUl4/LJWx/KEu0F2Mg==,iv:oY+q8R8dirzTjF4DFtzUss0VsVw78tjwZ1lmQLY8uWA=,tag:02QuaBb0CEtZBtwSPy4PZA==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieHU4UDhtWktURFpZZ2RI
            Z2NvUnczNkowcjVjaHFNTDVrMEt0ajFuUm5jCjA2ZDg2WlRlWmVkVTJNaklTM2lV
            WjRaRVl1WndYd29mV3ZPMTFPNzdWWVkKLS0tIFArSGZiU1pVN0toazhvd2N0VjZw
            NHVhZjgrVGd6RlZ6c2V3aUJYak1uY1kKru005TtTCcWjW+mRKb1lg2wTO0wh3OiX
            w4QJ3K9lTD6ySQiPK08ksuysl/xftZY5VIP59KEbpv1V7O3/NlVv5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:43:20Z"
    mac: ENC[AES256_GCM,data:uAJCIyjrgvESNf4xGe1AHUB3Xd6DFmifn1Gyz1uGFtkAF0dVX/l49uf0ZbaO1nUM8nHyBGOeN152WLWVwCf+tPK8uRu53Sci7CJskR6GEFLfippmsdkrbLjWLL1eaAHC2JfXeOj8MR9tVqlXY9+N2EJFkTAeLhpZXhYI6eV8FmM=,iv:5yav4tk0L9zo8xCzBc9u7So6MeproCVt2mDzSvt4HX8=,tag:EkwNcjyQeSO9OVkEz0GlOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
