apiVersion: v1
kind: Secret
metadata:
    name: ai-voice-secrets
    namespace: ai-voice
type: Opaque
stringData:
    FIREWORKS_API_KEY: ENC[AES256_GCM,data:skiS2t0nHrMktqhUzhRxiX9iIsbVwVupqg==,iv:JTuPAg7mF0Eq9YzHuDc8aXk5W+FeLl3wHsXQ5Tk7n2s=,tag:Sb3pRPb0SuQif1LwhnyEIg==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:txtcBpgO9oSEwlKTa4GinVPjysgKPbveO4F0G8IY45MBl9DwHp4zV2oNLkw375+aWtLjV2/MFZBDYtdamZKhwBooWqs6/Gifhw==,iv:ouLbtY+/zS057tMz1y4zwaUWVKGGVsZzCufeBJnYvds=,tag:PorkuyrTSNIh7xT8rssjnQ==,type:str]
    ELEVENLABS_API_KEY: ENC[AES256_GCM,data:o8RSj8Lqu+gI7nmxHuxRefsX/Xr1x2V6tloo3f3vVW2sQn981LlFZlFL5gzyYIEDBRfj,iv:QBbtoBxDwgEAPqkAXmYhzb5PQjHZJno9cMhvm7VjA+o=,tag:cIGMQ7Oka06sU1rmEU+p0A==,type:str]
    MASTER_API_KEY: ENC[AES256_GCM,data:Y6XVGhUxLWxJ7dU5jldsHKABz/UcuCRqmR9m/3PXxx5Q5W+Bmjsl2YmswA==,iv:AjvbiY0KSQZ5eV5DAyC9AX174HkaGVsUuDU3POFyMVY=,tag:Q5wDnmPFf3mxVEcw2OBFeA==,type:str]
    VITE_API_KEY: ENC[AES256_GCM,data:TcL1NxYDoLwaFLuHH9PGsfQWzsWSnHR4Dw8PyhZwgVgW4pJCDg==,iv:18/KQtV3aomWqOOmoyysT4Qfvj3g5XFvbMmH+Pf38ks=,tag:8E0BchM+fbPAuvittkZiCQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:xlBsoncM3r4=,iv:oWK0tx8HcGU+J3Ol/GInxrsxD1Ff/ixEfATafFu/AyQ=,tag:8wC3lOYg+iETfemJGiCagw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:B5gfAObX3LguakWu6DHr7HnNg/3LvNFmQZxxcX40Q8bI+JJwfg7l53/4ESoFJyQdM+SHfmmINOSjuPPwy8oleLcjwLmupLqB,iv:akaukv8zbwLYXLqpToVSNofz0Bcg/YDSrCbZpX3/7N8=,tag:iYJQeJ4DrCiMr91DzoQPpw==,type:str]
    API_KEY_HASH_SECRET: ENC[AES256_GCM,data:NXIpY4369/Go48ek/Oq/v5uFBOnAE89HSpboI0ZHX6ag4So98vALoVs4nA==,iv:/V4MFc63S0C5YufLHL69vaEcTh9/2UVVcyWh9lKNHs8=,tag:iaiH7U4lKWBcarRxlgvJiw==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQUZDT0tsQjVLVUwxVFV1
            VlpydHNrT1lLSnJTcW5IdlZIQzEvak5LNlRRClozUDFiUDhKODN5WGl1SCtWeDhm
            eGIrVUp2T3JReGp2V3BpTlgvMU5SR2sKLS0tIGNBa1QrNlFWcENQTXloZTAraUR6
            UDIxempSQVQweVYvVm1NWDlHRHM0NkkKozH7IVBNc5Ok+MGqJBdScAOXNIJXMKk7
            DhzhqJe4/kdDUCirPja2QkZTQq6RdCR9xrGE9C92LmL7uPi3dxcAuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:06:50Z"
    mac: ENC[AES256_GCM,data:iPlbVGfzsyq7w0+EQeHsByEjI7fnn2lL8I8aPADjPU0WiI+QGSkqfk6o2mzIhaHhjN235qtc6Z74ohCT7K5abGM8WZM4nFTgiltVRbvDnMV9MJUqHTmarQU+YzjDk2WnMkNpxH7buOIfmEqh90vGIl8qtQVeHCCgYxyhTTl5pkk=,iv:3Qto4O7BmW8qs1T7hJsrsICr/wXdWE0oW16dQpTaoas=,tag:083/f79bWBu+y8IIramQ2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: ai-voice
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:qx+Be+XBbw8XI2C5H8IbsJAV8whI6OpuOyR/XmQOdJCFuq2fg7uXzx2OrN3xislI6/h99BL2XN3g4j5d/lrwzVE3rcZKPMt86aS2Q+DBNQhjC7jinMVLUkl/jH7x88oNfKedM0ecK4TwerptO+72JB3DCLDG6y2qd/Ky0HD/d0aKbVTVVai6Uz6mCld4A1pDSf1V1XWIaf84/UlXpvXxlkgCsGFOeRrRbPuXDg==,iv:pvN6TWGP6UoGRbJwgzt6uFZgIUW0lM9B3xmnKBTrkHQ=,tag:nyvhDN8IfNHMwkscrAEtcw==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQUZDT0tsQjVLVUwxVFV1
            VlpydHNrT1lLSnJTcW5IdlZIQzEvak5LNlRRClozUDFiUDhKODN5WGl1SCtWeDhm
            eGIrVUp2T3JReGp2V3BpTlgvMU5SR2sKLS0tIGNBa1QrNlFWcENQTXloZTAraUR6
            UDIxempSQVQweVYvVm1NWDlHRHM0NkkKozH7IVBNc5Ok+MGqJBdScAOXNIJXMKk7
            DhzhqJe4/kdDUCirPja2QkZTQq6RdCR9xrGE9C92LmL7uPi3dxcAuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T16:06:50Z"
    mac: ENC[AES256_GCM,data:iPlbVGfzsyq7w0+EQeHsByEjI7fnn2lL8I8aPADjPU0WiI+QGSkqfk6o2mzIhaHhjN235qtc6Z74ohCT7K5abGM8WZM4nFTgiltVRbvDnMV9MJUqHTmarQU+YzjDk2WnMkNpxH7buOIfmEqh90vGIl8qtQVeHCCgYxyhTTl5pkk=,iv:3Qto4O7BmW8qs1T7hJsrsICr/wXdWE0oW16dQpTaoas=,tag:083/f79bWBu+y8IIramQ2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
