---
- name: restart sshd
  service:
    name: "{{ 'sshd' if ansible_os_family == 'Alpine' else 'ssh' }}"
    state: restarted
  become: yes

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
  become: yes

- name: apply firewall
  command: /usr/local/bin/firewall.sh
  become: yes
