---
- name: restart tailscaled
  ansible.builtin.systemd:
    name: tailscaled
    state: restarted

- name: reload systemd and restart udp-gro unit
  ansible.builtin.systemd:
    name: tailscale-udp-gro
    state: restarted
    daemon_reload: true
