---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fisense
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: fisense
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: GHCR_USERNAME
    - secretKey: password
      remoteRef:
        key: FISENSE_GIT_TOKEN
