---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: kite-secret
  data:
    - secretKey: KITE_ENCRYPT_KEY
      remoteRef:
        key: KITE_ENCRYPT_KEY
