---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kite-secret
  namespace: kube-system
spec:
  encryptedData:
    KITE_ENCRYPT_KEY: AgBbCvaZRAkbqv2RlfaEi11MnT+E2WukAaBAjlrnqPg+iBNdMsLQ7dKyvFU7t97mX4BVEJltPqh006IbFb0AjwlXUOTCDKsFvwLIIFTDEkNNO3IbUp7vo+xTI2tEhOjcbKXjCiZ3WUNlvEhwWhgL2oVrFYGWpWXqMXDrrRUX4ptGXrzsa51hM6ieWbBM2ppkj4eq3nfgZwr0YFpL3lIbzVHefIi76QxsB0ts6k0elVlvV0vb1GXMeoc90vCzTfbP16lAtxNZI5S+TDZGDJYaIDIDUQZ1sI1rWUaq6xCyKngjCleEvIyZoAPB3qwfVK/MYOJFMiiMp4/1Ka3pp6HrDvmEtQVqKVGn7apYZvWLEfonwK/8aV/IuXwkh3KQe4/upbhHNM8QDYvDjHc2YElA9XWa3Wd6aQL9X5NryWOiNtszS6jt6YrnDQwXPQ8pmWudHkYY+XFDCu96YC7iS5adVbDiI01mvvnaphHHlAC29+W9WZA9ajT4kFtUy4jZ5qP7MQzBwGnwX3CaQb1LXU71am1hj2ryIn6MadG4jdJ3nis4gH+CToYv4ptPjF8YwbHHa5AbEbtz6Sr5zlhR/TtWzyQnM/ZN+HHkHqwLGaOFZamg98L0/q7ydiBi6p8uuCqOJKVpJcmMzyJiMjLNctiq4o/HFVlf/UsXREsglf/Bv+FxWc9PaTCcVKaKF3YOFr0wDzPRXWLt/ySyVlnb39nzBnM9vgKHusz/jse08yRMxinfD4dV6x4njHGTnrxXY+ROasp1EP3Odwwnn+KSQBcSCHFW
  template:
    metadata:
      creationTimestamp: null
      name: kite-secret
      namespace: kube-system
