---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kite-data
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: piraeus-storage
  resources:
    requests:
      storage: 1Gi
