---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kite
  namespace: kube-system
  labels:
    app: kite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kite
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kite
        app.kubernetes.io/name: kite
    spec:
      serviceAccountName: kite
      containers:
        - name: kite
          image: ghcr.io/zxh326/kite:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: KITE_ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: kite-secret
                  key: KITE_ENCRYPT_KEY
            - name: DB_TYPE
              value: sqlite
            - name: DB_DSN
              value: /app/data/dev.db
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: kite-data
