---
apiVersion: v1
kind: Service
metadata:
  name: firefox
  namespace: tools
spec:
  clusterIP: 10.43.1.5
  type: ClusterIP
  selector:
    app: firefox
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: https
