---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secret
  namespace: utils
spec:
  encryptedData:
    SEARXNG_SECRET_KEY: AgBR3sSGWMhuC64K79vVa8mE8K0KjGrYfP8D3kV6I3PslVieevSk44ZIMHNqPT0otIyr8CffZmMpvCou0WUk/RZpqbC0ajsDzNxyaIlUVUJ3eTri78742BPZ6LXLR6noA1K9kyETBX74muqBSTBXcqhjeRY3hcjZMsBfEB9HsV8RfSMG8vCEm2FQ1qLHWzXUXIjgdgn2OOynypI9EHgE5RezxUlgyqz83aaQNPrQvnEuyNT4Bf2FvuXZQJ50z1Fq7VoI0cOMWRUs4en5M1Ym/ruMom9ydmwNqKPosr139Wc2Ybs3+R5kvlcb1tiNsA8ikCHSL7K5Ut+04eowHxErkGOFbiJuAasl7DWFWpmIq3K7crWtEEPXUDRfA+y/V7RhkEqbfWYuSG4KcqStMZ0aok0gVelEi7UBGUSaZ5ySEMKJCdE8UedT758zCStwMhp0W0NDyBkDWMD8wmyBZKEtAUyZDPr0aW/TCcli+RxIqehjy+EQ+mWEbsDAkfyTiJo/I0AprB+9MpxnAR0S36p/s8cYKbOhAFD0oyhjhADfx9WZHtdXS3McAtkU+krOlcG3IxGsbAWsFpuFFjkjr0xf1wHwTNSePjXI5JsIfcz1u34/swPmHH5QvO0K59wttkQVoJY93zYN9SlB+5pvF1CHzVRlUy8dvBHW3aqyw+JXvpTOFCKTcoNSoGKpmhoXl1dlTCIEs5g1YMUZbJB++XjHGX+CbQzUZ3WhW4o2aeEH7R3gmCs+rAVtkM90GoxT7fS+kXAlZiYxA269cpAvDIeDITa3
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secret
      namespace: utils
