---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-secret
  namespace: utils
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: searxng-secret
  data:
    - secretKey: SEARXNG_SECRET_KEY
      remoteRef:
        key: SEARXNG_SECRET_KEY
