---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng-redis
  namespace: utils
  labels:
    app: searxng-redis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: searxng-redis
  template:
    metadata:
      labels:
        app: searxng-redis
        app.kubernetes.io/name: searxng-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - --save
            - ""
            - --appendonly
            - "no"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: searxng-redis
  namespace: utils
spec:
  type: ClusterIP
  selector:
    app: searxng-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
