apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../kube-system/external-secrets/03-clustersecretstore.yaml
  - ../kube-system/external-secrets/04-clustersecretstore-her.yaml
