services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    hostname: sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=${UPUID}
      - PGID=${UPGID}
      - TZ=${TZ}
    volumes:
      # Sonarr config
      - ${HOME}/dockerc/mediamanager/sonarr:/config

      # Mount entire media folder (includes SSHFS mounts)
      # Access TV shows at: /media/mediaa/tvshows and /media/mediac/tvshows
      # Downloads at: /media/mediaa/downloads and /media/mediac/downloads
      - ${HOME}/media:/media

    networks:
      - public
    # ports:
    #   - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    hostname: radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=${UPUID}
      - PGID=${UPGID}
      - TZ=${TZ}
    volumes:
      # Radarr config
      - ${HOME}/dockerc/mediamanager/radarr:/config

      # Mount entire media folder (includes SSHFS mounts)
      # Access movies at: /media/mediaa/movies and /media/mediac/movies
      # Downloads at: /media/mediaa/downloads and /media/mediac/downloads
      - ${HOME}/media:/media

    networks:
      - public
    # ports:
    #   - 7878:7878

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    hostname: jellyfin
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=${UPUID}
      - PGID=${UPGID}
      - TZ=${TZ}
      # Published server URL (for remote access)
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL:-http://10.6.0.100:8096}
      # Transcoding optimizations for Android app stability
      - JELLYFIN_FFmpeg__probesize=50000000
      - JELLYFIN_FFmpeg__analyzeduration=50000000

    volumes:
      # Jellyfin config
      - ${HOME}/dockerc/mediamanager/jellyfin:/config

      # Mount entire media folder (includes SSHFS mounts)
      # Access all media libraries: /media/mediaa and /media/mediac
      - ${HOME}/media:/media

    # Transcode cache in RAM for mobile device compatibility
    # Needed when mobile clients require format conversion
    tmpfs:
      - /transcode:size=4G,mode=1777

    # Increased limits to support mobile transcoding
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 1G

    networks:
      public:
        ipv4_address: 10.6.0.100
    # ports:
    #   - 8096:8096  # Web UI
    #   - 8920:8920  # HTTPS (optional)
    #   - 7359:7359/udp  # Network discovery (optional)
    #   - 1900:1900/udp  # DLNA discovery (optional)

networks:
  public:
    external: true
