---
glusterfs_brick_path: /mnt/storage-brick
glusterfs_mount_path: /mnt/storage
glusterfs_volume_name: media
glusterfs_total_quota: "525GB"
glusterfs_init_node: systema
glusterfs_peers:
  - systema
  - systemb
  - systemc
