---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secret
  namespace: utils
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: litellm-secret
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: LITELLM_MASTER_KEY
    - secretKey: AGENTROUTER_API_KEY_1
      remoteRef:
        key: AGENTROUTER_API_KEY_1
    - secretKey: AGENTROUTER_API_KEY_2
      remoteRef:
        key: AGENTROUTER_API_KEY_2
    - secretKey: AGENTROUTER_API_KEY_3
      remoteRef:
        key: AGENTROUTER_API_KEY_3
