---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: utils
data:
  config.yaml: |
    model_list:
      - model_name: agentrouter/glm-5.3
        litellm_params:
          model: anthropic/glm-5.3
          api_base: https://agentrouter.org
          api_key: os.environ/AGENTROUTER_API_KEY
          extra_headers:
            user-agent: Anthropic/Python 0.117.1
            x-stainless-lang: python
            x-stainless-package-version: "0.117.1"
            x-stainless-os: Linux
            x-stainless-arch: x64
            x-stainless-runtime: CPython
            x-stainless-runtime-version: "3.13.5"
            x-stainless-async: "false"

    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY

    litellm_settings:
      set_verbose: false
      json_logs: true
      request_timeout: 600
      num_retries: 0
      max_connections: 20
      max_keepalive_connections: 10
      keepalive_expiry: 300
