apiVersion: v1
kind: Secret
metadata:
    name: open360-secrets
    namespace: open360
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:Fdl8SxkYayaWyi12fw8fBBf5Gz2Mdfo0JlrHQXZCJyGztpO2G7yA55s6FWKIt886WzvpYy7yeKOzMpuzWw13JGBgZdoz1WqUEw8vvhgYNBxmXxQ5x0XsVf+ikkE/uasrxAm9QtC9p/Yb7UmIyPNR+MUA,iv:qpu2U1GphpW9ccMGXskDxVYFW8zyFoRNMXroe4LqI0A=,tag:0yfmB3/ToEIjymt4SYGUDA==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:jZax2Tt/kVIBxPIStgyH7Z/PbE/RbAg/aRcBs/KuWNwa9Lxl+HLAFYGfmY0=,iv:XJKPT99CTbIYQZBV5irrdfkFi73dS5RNS5bYCVBBa3U=,tag:LkrVx0UiRrN9SZv2HiXYSQ==,type:str]
    NEXTAUTH_URL: ENC[AES256_GCM,data:ciq7C375LAwPr/UR5Co7r5x9LaXDALwzAVIqlLPu,iv:DEPkLbudCaifyUkyFi4VSdY8uD1tLgXJGAfkpo7QMvw=,tag:5/Lzq3uVGfAjKCWulOiMSg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:VYMPjK4Hu7plzIPfg2r0LU428J56ofcMx+GyfwA1XjcDepkjYa8gz/h39C398Dzl9aP4DBXBSWocjDuGlcpK3AuS0DMURT/P,iv:j3wesXMVrVR7+TIppGwtrNFvVq5jrVeFsyCNYKsRGBs=,tag:/TntglhrQcLhE661QXErnA==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:hRpT54foo7qut4Q323MBvw7A0dHtzik3AasDEIkaIjt+40M=,iv:z6nG1W8LoHaoZXqI+MxUjDCBtVAqJKCgtQbzJ6Zsywg=,tag:Zg63bNnZGIbRfoxxb8Zgiw==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:bIb8QSfF3NhPiU4Rhr0=,iv:AkYLpbLW+djog4UJwURVdHjNG0Fc1nf83KXFUdo95H4=,tag:gaWoKUDO7FuHP4BJU8ikhw==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:B4Ar,iv:B3zcfGunhr/FygqF5IGUdAPVBi5B9m8PKRZ4ieW8agQ=,tag:GunTHN+tzhXgk1KXjm3vxA==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:bRhx182m6okZoEnRp7WetBnFwm8=,iv:d710vB3MiR8gwnVvBkHzWipMVqBRCWcbmqq2Ch86JZM=,tag:m6qE520yfpamTv5B9+87oQ==,type:str]
    SMTP_PASS: ENC[AES256_GCM,data:/+jGvZNpoUlQZiLF2u7VvX1NHg==,iv:TT/ytv0i6qr6f0hsfLAO3UH+J55GhSPh3MRS3KsAJPE=,tag:zEBVB647L2kjZZITMQOhXw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:N2ZlQ/2qIMFVwF2naV3Iqg0w7lA=,iv:0te5aIkAcoEhAUPyHjoZObOm6czHQTknErvUKW4yqgE=,tag:7o3sZ64xDyXCYN12PuqPzQ==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:3IREDhSOngTd9dd77u64D54DbA1DX9fG/SBPe71EztZfaymNx9O5o3feERw6i1lDaXOdbw7+888A/MJid+FsJQ==,iv:BymXJ9hN1smMB6H/LAqu0/zjkssexQs+5prm7zLc/YU=,tag:Oc+HUiagK26EAoi/IQ/QNw==,type:str]
    CRON_SECRET: ENC[AES256_GCM,data:lbu7jWjNV7WA17foog6+mYqJTOUdeUqnL53wBC/B8qg=,iv:5bJSFdbePmsqOdje6p98GxuFiTHSik0EW2myjxfObRg=,tag:wST7A/mNvrnmXm6DqeY0Nw==,type:str]
    FIRST_ADMIN_EMAIL: ENC[AES256_GCM,data:+Fq2DHWnzHVSd3Ja3GooxZecmRA=,iv:YZj1UTA2JnnNGhpe+S1rc/aYFcuXd/eOCOFYSE45Dok=,tag:eUyi/ndefsJVCTm3j7OKHw==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGbDNZeG1jdUdPaElmZksw
            M0YreW1zQVc0SElLcDRWWHRXOVFEMDZWZ0NZCmJPNWxwL1BmM0lianZlcWNRdHVQ
            amkvVkZSVi9XTHRFSmFWWC9BZnBZaXcKLS0tIHM0R3NrWlp3TmFGZ0F1TFBSK2I1
            dUQwYkNRM1Bhek5TUzNHQTFaS09WaTgKDnhQDAPx0g20Kp03HSeobrjEiFJUZEm+
            +t9SP/uzUM1OkNgZ9ZBPj4DRZWFGP5VK3SpYjkTjCroMp9Uwao5sDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T08:12:03Z"
    mac: ENC[AES256_GCM,data:bbaXUNoKEn3gxXclSTjufH3SHODBOHYow7Mz1MmPTvJFc5OpUDdu4xCzWM9D+nFTIyu2FuzrTRuj+f8Ivmrz3MMK8do+B86ni9RMdf7oTv/cwyr8TjDM7GNjCmwVrG3QbJlcR+uFzhTvTSAl+6716Fh1oAfEtaZhponytJ2VBvQ=,iv:o4bfjOlQmxEH4O2/vMo7UQ9JHjOoql1TP1J83WvOJak=,tag:fW8UCqU7CLcqjWPfev75/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
