apiVersion: v1
kind: Service
metadata:
  name: open360
  namespace: open360
  labels:
    app: open360
spec:
  selector:
    app: open360
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
