apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: open360
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open360-redis
  template:
    metadata:
      labels:
        app: open360-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: open360
spec:
  selector:
    app: open360-redis
  ports:
    - port: 6379
      targetPort: 6379
