apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: media
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ZYsBHV4Es3igVR8pwMdL+3hjbnZN5wsuCrSNxQdDZ/7kLllPoORh0agpNdg2RaNVVPKSIPv2tnhmgxWQQ3lIQtqqoEoxFEW5tfHUOkIQnHP1wSflIU2VNFQcgeTpRqOEb6eEWyYVsIT2C8RSyiGsFbzwDc0LdPjXcZkA4hlIv4KTK+TX2dBEpal65tFPqH3kzTet0KaKoIW7jR7e7reZU3pWfO0zW00Veib1WfJElQtfQDBwvA1rWKDEEzCdaHNkpuMqPaUgf9ys0zcGsn9Nons484nCTkdO5sLgRTQdLrcyZbFwgR8Fyg==,iv:FjYqEBeTQnbi83Nzy1FRj4NrJTHWCrSoDRlKn7VCfSI=,tag:4xydnYfo5ydW8f8X+XlTEw==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtV0x6OWhCODVWMlhBYnpz
            UExoMXpZMjlqS0V1dFR4L2dPdE94RmY4aG1ZClBCc3RoZ2lNdDkwb0ptMFBHamtB
            aU5EV1NhYUN3NjlMeHVVMzdmVFljeDQKLS0tIEtnc2NZOE1wQng2M1MxcnZhZVlL
            M2JxVFI0S0NKc2xxUFFocmlVWkpqZUUKu/zGPPWytiGRc2+NGf9Fg6TDYPnKP56c
            RZXYNVU8cAIxbimv3Em1TjwJqiAlJ374yFMDRBXp4VujLCvobPemTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-01T14:57:07Z"
    mac: ENC[AES256_GCM,data:zL/DnwbcIENTgBuGif+XAJCy53bHHiSYdSHIQZS21+Rw93AgmQAWa6U5e8ENf/kHdMyj9/gqWQqBEXOSEz4yzM2OTsUvDbK8lB5AauYRm61B+da9yke2mTvKUpSC2nUgKlJPtiqUtDCOqpD7P2w3zG8kwMPfir9loSBbU/wMxLo=,iv:2wlK9f0pXhn6p4BUJF+S0l8uZDUvHmJ4BGNO9f5LAP8=,tag:yus7mOJziywTIQTJaA1cuQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
