apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: media
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:vSr3/O5Y1C0/8kc1YrXxyeoJUlBn3/MOizSTYdK6vc4Ts1cINyH0EZTpUO2wWS0iaF7n3AN6U+PMqjwlEW23HRlvAQ5bnHypXvBP0PRbFS7tbHDG7/ozXAsRhvPSK9W5iKSuDiZqu0TlQ0bRVYt1IYTSid6odsDMJIDeM5hudyIt1UrT3LMaIAbb5DXNFfjm+kpmSu50CLuPJ9ya+3+VMr79toE5fnlIETjv9hoObpxdBIzyMI11d6jmeWyoEV+ojVPh+p5Lz5LXNlm82ATKNSryyYI2euuLxsdBPLEmAsvhW985qole0g==,iv:oPmXhLLvaktLjRQKgslLTkZxKp+wy36smVjkfOCzW0Y=,tag:P/nZ4kygXDU+9SweygtKYA==,type:str]
sops:
    age:
        - recipient: age1yl0pwtul6ph7xyaej0pqnmd6enflx50czvh4prudl2ed4vhn8u4scve65h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYnRQRkIzdG1JVnhpckJW
            UC94bm9MZkVmTlEvOVhqcFRnVi9Wb3ZBMUNjCmcrVi9jMUswQzVBMmU3QUg1OXlO
            cWFKWFlTd3M3S1JqeXprZXVkNHF0YXMKLS0tIG1ieGUvNUpzZS8wc1E5eUF3Uncy
            MFpMRjBQRXErVUl1SytxUHBpMjNLQm8KdXhkuwJqwT94GzO14+hcABDsV8rKYLN2
            TBeXv1ah5bfEB+FO1Aqtj/LbWbtJaZFxofkV9GsPlG9Y9zROA2hhYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T04:05:27Z"
    mac: ENC[AES256_GCM,data:bEoaZxR7Qkz6fCMH08/wHFJBTmLk71xwe/srQqn7EkY5Yki+VZRtQbQs0zXwj47a5R76Fl9NKVXdalW8v7EF6bGotAN5enF9NYo/BNOTVyiM93NbBsLeDzSkacNluKgZXPg5CknMCVPeIDe7FCGAHKAGjtuJ6/xgyz+iK/RNCFg=,iv:MFP4+msxaOwmvixHiNiaAjQl+p95+6DM0xTPFA9lMFI=,tag:LmJSaSXuAIJnQzhsVW3oMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
