---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: media
spec:
  encryptedData:
    .dockerconfigjson: AgATxZaO5B223S8dTrsxBp70FMRWir8DcmU6gsK4EjuvErtZk+Wkn8v5HfkXq1wLb45fYqsMX3cXBjoOS55Svv5uA+p0HD/2R5p0mByN5WWTP3gBDh6Gt3f73Z63Y308vzXjVHM+/OqMXeawKqLtoXRU0isXdgUyYUzSopIxJA7vUsv0CLe513i2GY/9REbg7lLSppz67w5lJYXSzGnDDrBjdEij4VJTcIKjmFQlqJo4qZKn7WZV9M3JvUGe7v7fgvv/gIGb3jzeA5qzyZA5h/LNkcwcOTIFPc7GqGnL9kHRmdDvzW7bWuBVB7g4DqyE5dDrAQKyvlmhOc9ggqS/MFvLif7txXazxqpcWd4v/AX+F9fjpsedfRXDzr2XEjyrYCreJHMtnZ0bZW1+UprfyioiIWr8z8Iygrfdrq5DdRjvLuV7Bm2MHkPR93MXt23YC2orZFvSEPOR9hzKTM2qGHmsnVg7YnnBT4U1ot2V9JLZzAOVHhCG6MpOv9kziCuxGIYogT5HTer8JjDAIXtTsK6JyHPoLjfarkLw2xB+jBBZK2fqvWukOFdq5ar7WzfqDD0aOADPQmaXKjVlU6vqWvvo7BQj+U0rSpPEjl5GjjGH+ELplEyE+/9whwTOV9hktpOAgkSBDsrEHYQjDf+547BbIRm+cE+nzGrmyHNOMF7KqWbbpYasjtGsvt3V2ZutQAu6PIbkHtgfGUkCeC39qck0W4ryfrxNeN5I1AW6viKkf+llxozwGkXFRU3Fkg+dOpsyCWzyVcMBQazLzyZg1Zuh7Ff/e0/SZqXNeO3klyCAmrVkyrglOC3PDCQ2wAqjch9QaZ/plb7GKyxQAp7SAHqaSE3XhYX+mqK6xXhNkUPR2n0HFh6AyGwrF27WsOUhPapDExvjNFPXT/Fax65B97rIjvuXjAYSaoVobqhZ
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: media
    type: kubernetes.io/dockerconfigjson
