---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: utils
  labels:
    app: n8n
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
        app.kubernetes.io/name: n8n
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5678
          env:
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_HOST
              value: "n8n.rogx.cc"
            - name: WEBHOOK_URL
              value: "https://n8n.rogx.cc/"
            - name: GENERIC_TIMEZONE
              value: "Asia/Dhaka"
            - name: N8N_RUNNERS_ENABLED
              value: "false"
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret
                  key: N8N_ENCRYPTION_KEY
          resources:

            requests:

              cpu: "100m"

              memory: "256Mi"

            limits:

              cpu: "1000m"

              memory: "1Gi"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-pvc
