apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oci-billing
  namespace: oci
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: oci-billing
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        config.yaml: |
          telegram:
            bot_token: "{{ .bot_token }}"
            chat_id: "{{ .chat_id }}"
          accounts:
            - name: "rafsunx"
              tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaaj3evzhw4qeo3lsv3rftlraq7k6jjb2ibjhrbamrq4q3vvyobbspq"
              user_ocid: "ocid1.user.oc1..aaaaaaaatqc443h5qrdxnccj6g6auokxmugykjnwxwodwzzfp3lnwunkrh5a"
              fingerprint: "1b:87:84:8e:46:f0:50:e0:30:e5:0f:b4:ad:45:b3:fb"
              region: "eu-frankfurt-1"
              key_file: "/keys/account1.pem"
            - name: "rafsunxe"
              tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaa2bnlep5bazpezvqeb2lnqo4aw2ljhxszpbg6s7xxfpsjksp4u65q"
              user_ocid: "ocid1.user.oc1..aaaaaaaazffeznstu724svuhizojjqtgnrt7zzb3uvhrmoalbicmb6sf673q"
              fingerprint: "c5:ad:28:fe:47:9e:03:37:84:b3:6d:e6:34:e9:f6:26"
              region: "eu-frankfurt-1"
              key_file: "/keys/account2.pem"
            - name: "zisanx"
              tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaa324j7ooadnbe7ntzg2wqcharvy6cfj6rsvwvwyweuad6nkxxkygq"
              user_ocid: "ocid1.user.oc1..aaaaaaaa7b6uhvv2g2cp4k22phnjep6xspjywnsrjmj772fpmcw7wicdoqaa"
              fingerprint: "5a:1d:3a:a2:d5:b8:69:89:39:b3:31:bd:4c:f2:33:a4"
              region: "eu-frankfurt-1"
              key_file: "/keys/account3.pem"
            - name: "khokon"
              tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaacwruueirxtql33z4brfokcfehuz4d5vepsvv7nvcdibwd6ur2a2a"
              user_ocid: "ocid1.user.oc1..aaaaaaaauu3zyohe7fn6vtrfh4m4g4i4sw6gk6doxwa5fbv2tpxej2b4nuya"
              fingerprint: "15:d1:6b:5f:8a:a4:27:c7:b5:95:8b:22:ad:a3:25:0f"
              region: "uk-london-1"
              key_file: "/keys/account4.pem"
            - name: "ashfaqoni"
              tenancy_ocid: "ocid1.tenancy.oc1..aaaaaaaanuzp6ckoej4h4elgavpfa62fhdu44qv7oo7j4rjwm24f5nhxvgma"
              user_ocid: "ocid1.user.oc1..aaaaaaaa2strlfx6uatolvqtpjbdtvumih6cieyfszzxqluapii227tuvpaq"
              fingerprint: "bf:84:7b:6d:60:c3:83:cd:91:76:84:9d:eb:77:31:aa"
              region: "us-ashburn-1"
              key_file: "/keys/account5.pem"
        account1.pem: "{{ .key1 }}"
        account2.pem: "{{ .key2 }}"
        account3.pem: "{{ .key3 }}"
        account4.pem: "{{ .key4 }}"
        account5.pem: "{{ .key5 }}"
  data:
    - secretKey: bot_token
      remoteRef:
        key: TELEGRAM_OCI_BOT_TOKEN
    - secretKey: chat_id
      remoteRef:
        key: TELEGRAM_CHAT_ID
    - secretKey: key1
      remoteRef:
        key: OCI_KEY_ACCOUNT1
    - secretKey: key2
      remoteRef:
        key: OCI_KEY_ACCOUNT2
    - secretKey: key3
      remoteRef:
        key: OCI_KEY_ACCOUNT3
    - secretKey: key4
      remoteRef:
        key: OCI_KEY_ACCOUNT4
    - secretKey: key5
      remoteRef:
        key: OCI_KEY_ACCOUNT5
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-secret
  namespace: oci
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: ghcr-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: GHCR_USERNAME
    - secretKey: password
      remoteRef:
        key: GITHUB_TOKEN
