apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: nixos-config
  namespace: piraeus-datastore
spec:
  podTemplate:
    spec:
      initContainers:
        - name: drbd-module-loader
          env:
            - name: LB_HOW
              value: deps_only
          # Remove volume mounts that don't exist on NixOS
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
  storagePools:
    - name: pool1
      fileThinPool:
        directory: /var/lib/piraeus/pool1
