# Generated by nixos-generate-config — do not edit manually.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" ];
  boot.initrd.kernelModules  = [ ];
  boot.kernelModules         = [ ];
  boot.extraModulePackages   = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5d2aacbc-8a65-485c-8449-9aef1a56f6f3";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device  = "/dev/disk/by-uuid/3DBE-4235";
    fsType  = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
