---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TZ
              value: "UTC"
          resources:

            requests:

              cpu: "1000m"

              memory: "1Gi"

            limits:

              cpu: "4000m"

              memory: "8Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /data/tvshows
            - name: movies
              mountPath: /data/movies
            - name: gdrive-shows
              mountPath: /data/gdrive/tvshows
            - name: gdrive-movies
              mountPath: /data/gdrive/movies
            - name: hza-shows
              mountPath: /data/hza/tvshows
            - name: hza-movies
              mountPath: /data/hza/movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: shows
          hostPath:
            path: /mnt/storage/Shows
            type: Directory
        - name: movies
          hostPath:
            path: /mnt/storage/Movies
            type: Directory
        - name: gdrive-shows
          hostPath:
            path: /mnt/gdrive/Shows
            type: Directory
        - name: gdrive-movies
          hostPath:
            path: /mnt/gdrive/Movies
            type: Directory
        - name: hza-shows
          hostPath:
            path: /mnt/hza/Shows
            type: Directory
        - name: hza-movies
          hostPath:
            path: /mnt/hza/Movies
            type: Directory
