---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: media
  labels:
    app: jellyfin
  annotations:
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "100"
            - name: TZ
              value: "UTC"
          resources:
            requests:
              cpu: "2000m"
              memory: "2Gi"
            limits:
              cpu: "3000m"
              memory: "6Gi"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: shows
              mountPath: /data/tvshows
            - name: movies
              mountPath: /data/movies
            - name: pri-shows
              mountPath: /data/pri_shows
            - name: pri-movies
              mountPath: /data/pri_movies
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: shows
          hostPath:
            path: /mnt/storage/Shows
            type: DirectoryOrCreate
        - name: movies
          hostPath:
            path: /mnt/storage/Movies
            type: DirectoryOrCreate
        - name: pri-shows
          hostPath:
            path: /mnt/storage/pri_shows
            type: Directory
        - name: pri-movies
          hostPath:
            path: /mnt/storage/pri_movies
            type: Directory
