---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  clusterIP: 10.43.10.10
  type: ClusterIP
  selector:
    app: jellyfin
  ports:
    - port: 8096
      targetPort: 8096
      protocol: TCP
      name: http
