apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kite/01-rbac.yaml
  - kite/02-storage.yaml
  - kite/03-deployment.yaml
  - kite/04-service.yaml
  - keel/helmrelease.yaml
