apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn/00-namespace.yaml
  - longhorn/01-helmrepo.yaml
  - longhorn/02-helmrelease.yaml
  - sealed-secrets/01-helmrepo.yaml
  - sealed-secrets/02-helmrelease.yaml
  - kite/01-rbac.yaml
  - kite/00-secret.yaml
  - kite/02-storage.yaml
  - kite/03-deployment.yaml
  - kite/04-service.yaml
  - prometheus/01-helmrepository.yaml
  - prometheus/02-helmrelease.yaml
