apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-postgres.yaml
  - 04-migrate-job.yaml
  - 05-deployment.yaml
  - 06-service.yaml
  - 07-redis.yaml
  - 08-hpa.yaml
  - 09-log-collector.yaml
  - 10-cloudflared.yaml

images:
  - name: ghcr.io/rafsunx/her-server

    newTag: sha-147e571
