---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: cloudflared-token
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARED_TUNNEL_TOKEN
