---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: networking
spec:
  encryptedData:
    token: AgBoDEy6fxhnUmdVC1Sg69OsxdLVGEMvA8xHm4cWXpZvcUxhKj0eV3spfxU1QvJktLRRa0//DElaRXUYFA+iPq28msRLWFIzBz/u/Ykv80BaWAk0QvhKmuXQUuk0bHuGd8sOakvtbw9eQR/wBHUGeJLKjFuVZEOjkfSI5at0ER7GRy2XL2PagdodWb4tgpT9xx8urDKnwkG0yAHASDZ/ZWmgYvXz7Cz66FgKhswkyStlEQ5GPRZhHDN0SxGKcc8W6hEOcV1Yy32oDlCUg1wHhNPafE0fGGst5GsEaEuumfdmCAR4dSeU+9mez8+irlOf5dyrrapjCng4QUtrvZNA+melFYvmPgLsb3Pg9xZKXykN+r8+TeQZP5tYGFG+pgprJ9nJLC/LaxFzfxxr+5ODmnAn3HoCFrG1VaSxFCZdvHTDbbD7nHdJWakJukfO7m/Csd1S0BoBjxvblxcHQcQ7gT6DsI3hlBJm0mu33JG7EVgyc6manAxObLojE/Q04n6sSPGY7rbaJmkBkAD9zMgxnoeIrFuBmK5K0GSU3H1v+C7im+SSDDwlTpYMgl2pjjxaz4/E2gjIAo2VvwCeNEL10QQ2Zj66LjTqWEFy+o/00pxXVVlrBTV7IF6LSfsOdNaijMWWyZ17i+XVjIBY2wd+2box7/39qnvSNm6cIx2QYYS/WE3LUi3+TYsTbxT5Lhl5DVk7uXq0gbSoB9HiwKnWRGzwKsA7qQsHZzbU96uHLwVkig8+KZ31MObF6Y1RU93wmqOVgHFAm6d7S+Tk9qY4DrvuDlJ3Abx5XN0goGhaT8guQ8cbft+VfxB1/bSz81caGLWvpdy4UBCfyFMdO2sOSEuoEc7fnxwCFcYbApz1TG9I3orf1D1SKYLs+8Hxg3r5Bm++csw0RazcoaI9VL5hmLGN/Jiwo1OGL1GJkTgC8Tc9QGJhtflTYnkR
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: networking
