---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openspeedtest
  namespace: utils
  labels:
    app: openspeedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openspeedtest
  template:
    metadata:
      labels:
        app: openspeedtest
        app.kubernetes.io/name: openspeedtest
    spec:
      containers:
        - name: openspeedtest
          image: docker.io/openspeedtest/speed-test:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
