---
apiVersion: v1
kind: Service
metadata:
  name: openspeedtest
  namespace: utils
spec:
  clusterIP: 10.43.1.17
  type: ClusterIP
  selector:
    app: openspeedtest
  ports:
    - port: 80
      targetPort: 3000
