---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fisense
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/FiSENSE/FiSense
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fisense
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: fisense
