---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: server-hub
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/RAFSuNX/server-hub
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/clusters/main
  prune: true
  sourceRef:
    kind: GitRepository
    name: server-hub
