apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - namespaces.yaml
  - media.yaml
  - tools.yaml
  - networking.yaml
  - kube-system.yaml
  - default.yaml
  - open360.yaml
