apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - kube-system.yaml
  - namespaces.yaml
  - networking.yaml
  - utils.yaml
  - media.yaml
  - her.yaml
  - open360.yaml
  - hermes.yaml
  # - fisense.yaml
