apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: orangehrm
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 10m
  path: ./k8s/orangehrm
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
