apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: utils
  namespace: flux-system
spec:
  dependsOn:
    - name: namespaces
  interval: 5m
  path: ./k8s/utils
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
