---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: media
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 6h"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
        app.kubernetes.io/name: radarr
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "100"
        - name: TZ
          value: UTC
        image: linuxserver/radarr:latest
        imagePullPolicy: Always
        name: radarr
        ports:
        - containerPort: 7878
          protocol: TCP
        resources:

          requests:

            cpu: "200m"

            memory: "512Mi"

          limits:

            cpu: "2000m"

            memory: "3Gi"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /movies
          name: movies
        - mountPath: /downloads
          name: downloads
        - mountPath: /gdrive/movies
          name: gdrive-movies
        - mountPath: /hza/movies
          name: hza-movies
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - hostPath:
          path: /mnt/storage/Movies
          type: DirectoryOrCreate
        name: movies
      - hostPath:
          path: /mnt/storage/Downloads
          type: DirectoryOrCreate
        name: downloads
      - hostPath:
          path: /mnt/gdrive/Movies
          type: Directory
        name: gdrive-movies
      - hostPath:
          path: /mnt/hza/Movies
          type: Directory
        name: hza-movies
