services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    hostname: filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: "${UPUID}:${UPGID}"
    environment:
      - TZ=${TZ}
    volumes:
      - ${HOME}:/srv
      - ${HOME}/dockerc/filebrowser/database.db:/database.db
    networks:
      - public
    # ports:
    #   - "80:80"

networks:
  public:
    external: true
