apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-postgres.yaml
  - 03-redis.yaml
  - 04-deployment.yaml
  - 05-migration-job.yaml
  - 06-backup-cronjob.yaml
  - 07-sync-worker.yaml

images:
  - name: ghcr.io/rafsunx/amanat
    newTag: sha-e49c894ff28d5ce3a3c0ad720a6443f7083e32be
  - name: ghcr.io/rafsunx/amanat-migrate
    newTag: sha-e49c894ff28d5ce3a3c0ad720a6443f7083e32be
