apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-secrets.yaml
  - 02-postgres.yaml
  - 03-redis.yaml
  - 04-deployment.yaml
  - 05-migration-job.yaml
  - 06-backup-cronjob.yaml
  - 07-sync-worker.yaml

images:
  - name: ghcr.io/rafsunx/amanat
    newTag: sha-259eb8b4a66e6f0e2c01d71d1cb8a04e29a2d3c9
  - name: ghcr.io/rafsunx/amanat-migrate
    newTag: sha-259eb8b4a66e6f0e2c01d71d1cb8a04e29a2d3c9
