services:
  filebot:
    image: jlesage/filebot:latest
    hostname: filebot
    container_name: filebot
    restart: unless-stopped
    environment:
      # User/Group Configuration
      - USER_ID=${UPUID}
      - GROUP_ID=${UPGID}
      - TZ=${TZ}

      # Display Settings
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - LANG=en_US.UTF-8
      - DARK_MODE=1

      # Security Settings
      - SECURE_CONNECTION=1
      - WEB_AUTHENTICATION=${FILEBOT_WEB_AUTH:-0}
      - WEB_AUTHENTICATION_USERNAME=${FILEBOT_USERNAME:-admin}
      - WEB_AUTHENTICATION_PASSWORD=${FILEBOT_PASSWORD:-changeme}

      # FileBot Settings
      - FILEBOT_GUI=1
      - USE_FILEBOT_BETA=${FILEBOT_USE_BETA:-0}

      # Automated Media Center (AMC) Settings
      - AMC_ENABLED=1
      - AMC_ACTION=${FILEBOT_AMC_ACTION:-test}
      - AMC_INTERVAL=${FILEBOT_AMC_INTERVAL:-1800}
      - AMC_INPUT_STABLE_TIME=${FILEBOT_AMC_STABLE_TIME:-10}
      - AMC_INPUT_DIR=/media/mediaa:/media/mediac
      - AMC_OUTPUT_DIR=/media
      - AMC_MATCH_MODE=${FILEBOT_AMC_MATCH_MODE:-opportunistic}
      - AMC_ARTWORK=${FILEBOT_AMC_ARTWORK:-n}
      - AMC_LANG=${FILEBOT_AMC_LANG:-English}
      - AMC_MUSIC_FORMAT=${FILEBOT_AMC_MUSIC_FORMAT:-{plex}}
      - AMC_MOVIE_FORMAT=${FILEBOT_AMC_MOVIE_FORMAT:-{plex}}
      - AMC_SERIES_FORMAT=${FILEBOT_AMC_SERIES_FORMAT:-{plex}}

      # OpenSubtitles Configuration (Optional)
      - OPENSUBTITLES_USERNAME=${FILEBOT_OPENSUBTITLES_USER:-}
      - OPENSUBTITLES_PASSWORD=${FILEBOT_OPENSUBTITLES_PASS:-}

    volumes:
      # Application config and logs
      - ${HOME}/dockerc/filebot:/config

      # Mount entire media folder (includes SSHFS mounts)
      - ${HOME}/media:/storage

    # Note: /media/mediaa and /media/mediac are accessible inside container at /media/
    # Configure AMC to watch /media/mediaa and /media/mediac
    # Output will go to /media/

    networks:
      - public
    # ports:
    #   - 5800:5800  # Web GUI (HTTP/HTTPS)
    #   - 5900:5900  # VNC (optional)

networks:
  public:
    external: true
