---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: orangehrm-db
  namespace: orangehrm
spec:
  encryptedData:
    mysql-password: AgBJHwYtHjnJaPrKG+T8z4oZ2xLsx2+3gh34cY71Edmc74NxWExlkboRCBROo2XXA+cZRTUd90c969i9fqZhagJj1HH9YUEmoXswNPHAeypW/N4+yXkYNr1EC2rutUepwlkJpVy30JgiLz28mjIv5oavVK0xr/tg3g7ixAOuy/2wUvpdl8MXZ5AFzmVG6dnBOL4iAtcuezBXmwtp0wl/E0KbGSKHMwmVCqsw9hohLrPqdq5qUEPnm+TtpRc9NQgi0i6o58tNKB6oO4z4jCMAieyqteBlEZU6DxgTZV7D7M850PyP+WoWEsjrbhZ44dxnoNXk6L7P7Z8ljcmudC3Mvmi2Jfe7IQr6e9oj9pNhVfYN3xR/+97Rig5PQQWfIHUONNTrJ94/OQYu9n0u9My794Uz7vEQqEDxx9EXsNGdNalDQh2Rq43V5tTDbAwTiiWUxNhWMeMAS0qh2APKXDzTeJT5RcNjqgN8wViHbZx9miwDo0VsJ1JSCh9iTVPrnairtQlffGl+gN/zeRlkCDECafD8+Ps233rnCbbchVUDQ20wHKBjDujtRLIcthlgqlmBiIhX0E8RmQrQsWNt1P7iqCsiSp83Ppfq/aklQOhhKUE87P1L8uManAJNEf7zzdbZrVQ6gptDHLTLW6liToULUT4Sp0ILkKaveNYLC4q0ybVR+cWPCiaTaxZXEUzx9JH2JHoBk7T/ybU4RcJFmMS8kcnzf4tWNwUOluaWAP9BnwFO7XkEXTgqIcOP1ZnvkI6rHtY=
    mysql-root-password: AgA020Z/RaMlZZLUgns4kEx097OcI4wg8C0A1laM2FWhZPQuJpCsf6+Cq3Y9LdMRtdQjGwj2jupnG8CPjAxAOmfQb2auu4pf36d8Tcvm40o+A2U/cljhLIwndaj4FiPFW5dTo8b5pxC6IUL3ISmF6D4BCpldrhHb3uwlnum9r1UDUYdx8vkY5uvfEKuwowhWUC98a1URQxsEVd+gO6VYox8Y/z0fiaT5SneOBHuz0EneUc5hvOkujpPWGzhUVrAknlexO/6pUuhtD5NMf2q3heA1DN5mb3w7ikRqKSTG4MwHtq2ipTiHCZSbaa4ysLNqO57H3sPWX1nnJ4TJDFp+G4ZynaXuUxwqnjFt9yQzWQDHd5x0Ic/gJdfbGyllT34Otlplo3idnYsf0CQJCnEA4gGtz0CL2KCPAb/A3HRm7uQDawztTMywtGkpbYEiCEGI6mXDyruejk9FVjRtJI3LbLdBVubPBUBg//0Eh+4nYeQkvPUDQtWquIAhQuClkzLUmGDkuxJSEC9TPtw46MrVCf+WMmIlu1GeN7iPuZoWkGuRVrqmvLjQcByRZMm9lF8jUv8rQEMVd6kujAY4JJdbE/Y6MSQ2il4yyz48EcaXZZpvmbYylxDrWhVC9A4pl62kViGmieh3wRXUAqKxgZNhIFO4/knpNjqZOifUI8QYDJ+W9e3Iwu0aybPif/aSJQuXLNVlNHm3nuBbzC7o5ifP4wLU9rV+e0ZdTNEr9zJTi/WAc+Rcr5TK6xiOczHjrmK9fNY=
  template:
    metadata:
      creationTimestamp: null
      name: orangehrm-db
      namespace: orangehrm
