---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-backgrounds
  namespace: utils
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
