---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-vars
  namespace: utils
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler
    kind: ClusterSecretStore
  target:
    name: homepage-vars
  data:
    - secretKey: HOMEPAGE_VAR_JELLYFIN_KEY
      remoteRef:
        key: HOMEPAGE_VAR_JELLYFIN_KEY
    - secretKey: HOMEPAGE_VAR_SONARR_KEY
      remoteRef:
        key: HOMEPAGE_VAR_SONARR_KEY
    - secretKey: HOMEPAGE_VAR_RADARR_KEY
      remoteRef:
        key: HOMEPAGE_VAR_RADARR_KEY
    - secretKey: HOMEPAGE_VAR_SEERR_KEY
      remoteRef:
        key: HOMEPAGE_VAR_SEERR_KEY
    - secretKey: HOMEPAGE_VAR_PROWLARR_KEY
      remoteRef:
        key: HOMEPAGE_VAR_PROWLARR_KEY
    - secretKey: HOMEPAGE_VAR_QBIT_WARP_USER
      remoteRef:
        key: HOMEPAGE_VAR_QBIT_WARP_USER
    - secretKey: HOMEPAGE_VAR_QBIT_WARP_PASS
      remoteRef:
        key: HOMEPAGE_VAR_QBIT_WARP_PASS
