services:
  pelican:
    image: ghcr.io/pelican-dev/panel:latest
    hostname: pelican
    container_name: pelican
    restart: unless-stopped
    networks:
      - public
    # ports:
    #   - "80:80"
    #   - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${HOME}/dockera/pelican/data:/pelican-data
      - ${HOME}/dockera/pelican/logs:/var/www/html/storage/logs
      # Uncomment the line below if you want to customize the Caddyfile
      # - ./Caddyfile:/etc/caddy/Caddyfile
    environment:
      XDG_DATA_HOME: /pelican-data
      # Replace with your actual domain or IP
      APP_URL: "${PELICAN_APP_URL:-http://localhost}"
      # Replace with your email
      ADMIN_EMAIL: "${PELICAN_ADMIN_EMAIL:-admin@example.com}"
      
      # Redis cache configuration
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      
      # Optional: Database configuration (defaults to SQLite if not specified)
      # DB_CONNECTION: mysql
      # DB_HOST: mysql
      # DB_PORT: 3306
      # DB_DATABASE: pelican
      # DB_USERNAME: pelican
      # DB_PASSWORD: your_secure_password
    depends_on:
      - redis

  # Redis Cache
  redis:
    image: redis:alpine
    hostname: pelican-redis
    container_name: pelican-redis
    restart: unless-stopped
    networks:
      - public
    volumes:
      - pelican-redis-data:/data
    command: redis-server --appendonly yes

  # Optional: MySQL Database (uncomment if you want to use MySQL instead of SQLite)
  # mysql:
  #   image: mysql:8.0
  #   hostname: pelican-mysql
  #   container_name: pelican-mysql
  #   restart: unless-stopped
  #   networks:
  #     - public
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "${PELICAN_MYSQL_ROOT_PASSWORD:-your_root_password}"
  #     MYSQL_DATABASE: "${PELICAN_MYSQL_DATABASE:-pelican}"
  #     MYSQL_USER: "${PELICAN_MYSQL_USER:-pelican}"
  #     MYSQL_PASSWORD: "${PELICAN_MYSQL_PASSWORD:-your_secure_password}"
  #   volumes:
  #     - ${HOME}/dockera/pelican/mysql:/var/lib/mysql

volumes:
  pelican-redis-data:
  # pelican-mysql-data:

networks:
  public:
    external: true
