---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ariang-config
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: piraeus-storage
  resources:
    requests:
      storage: 1Gi
