---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ariang
  namespace: tools
  labels:
    app: ariang
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ariang
  template:
    metadata:
      labels:
        app: ariang
    spec:
      containers:
        - name: aria2-ui
          image: wahyd4/aria2-ui:latest
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          env:
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: tools-auth
                  key: password
            - name: ENABLE_AUTH
              value: "true"
            - name: ARIA2_USER
              valueFrom:
                secretKeyRef:
                  name: tools-auth
                  key: username
            - name: ARIA2_PWD
              valueFrom:
                secretKeyRef:
                  name: tools-auth
                  key: password
            - name: ENABLE_FILEBROWSER
              value: "false"
            - name: ENABLE_RCLONE
              value: "false"
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "8Gi"
              cpu: "4000m"
          volumeMounts:
            - name: downloads
              mountPath: /data
      volumes:
        - name: downloads
          hostPath:
            path: /mnt/storage/Downloads
            type: Directory
