---
apiVersion: v1
kind: Service
metadata:
  name: ariang
  namespace: tools
spec:
  clusterIP: 10.43.1.4
  type: ClusterIP
  selector:
    app: ariang
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
